### ISSUE TITLE
2019/05/18 - ソースコードレビュー

### ISSUE THREAD

**Issue by ghost** [Yumihiki/pdf-uploader#2]
## upload.html
- max_file_sizeはバリデーションで利用するものかと思いますが、サーバー側に持たせてあげることで、formでの送信は無くしていいかなと思います。

https://github.com/Yumihiki/pdf-uploader/blob/775cc8729c354b109dc4b627f92bb11febba125a/upload.html#L20

- acceptを利用して選択できるファイルを制限することが可能です。サーバー側でチェックすると思うので、無くても問題ないのですが、ユーザーの利便性という点でacceptを利用したりします。
参考URL: http://html5.cyberlab.info/elements/forms/input-accept.html

https://github.com/Yumihiki/pdf-uploader/blob/775cc8729c354b109dc4b627f92bb11febba125a/upload.html#L21

## upload.php
- Classやfunctionを利用したコーディングを検討
→  オブジェクト指向を用いたコーディングができるかどうかは評価に関わるので、PHPはなしでコーディングできてしまいますが、できる限り意識したコーディングをした方がいいです。例えば今回の場合は、ファイルアップロードの制御を１つのClassにまとめるとかですね

- 定数定義を検討してみてください。
参考URL: https://qiita.com/Hiraku/items/bb0cb665d830f7cd37ff

https://github.com/Yumihiki/pdf-uploader/blob/775cc8729c354b109dc4b627f92bb11febba125a/upload.php#L7

https://github.com/Yumihiki/pdf-uploader/blob/775cc8729c354b109dc4b627f92bb11febba125a/upload.php#L10

**Comment by nibuno** [comment]
レビューありがとうございます。今週はこちらの指摘いただいた点をまず取り組んで行きます！
